import {spawn} from 'node:child_process';
import {mkdirSync,mkdtempSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=resolve(import.meta.dirname,'..'),url='http://127.0.0.1:8894',out=resolve(root,'evidence/desired-home');mkdirSync(out,{recursive:true});
const server=spawn(resolve(root,'.venv/bin/python'),['-m','floorforge','serve','--no-browser','--port','8894','--out',mkdtempSync('/tmp/ff-desired-test-')],{cwd:root,stdio:['ignore','pipe','pipe']});server.stderr.on('data',d=>process.stderr.write(d));
let browser;const checks=[],errors=[];const check=(name,pass)=>{checks.push({name,pass:!!pass});console.log(pass?'PASS':'FAIL',name);if(!pass)throw Error(name);};
try{
 for(let i=0;i<100;i++){try{if((await fetch(url+'/api/session')).ok)break;}catch{}await new Promise(r=>setTimeout(r,200));}
 browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});const page=await browser.newPage({viewport:{width:1512,height:1050}});page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url);await page.waitForFunction(()=>document.querySelector('#workspace-project option[value="sample:my-desired-home"]'),null,{timeout:180000,polling:100});
 const original=await page.evaluate(()=>({build:window.__ff.buildId,project:window.__ffApp.collect()}));
 await page.selectOption('#workspace-project','sample:my-desired-home');
 await page.waitForFunction(()=>window.__ff?.buildId==='sample:my-desired-home'&&!window.__ffApp.draftStale,null,{timeout:180000,polling:100}).catch(async e=>{console.log(await page.evaluate(()=>({toast:document.getElementById('toast').textContent,build:window.__ff.buildId,state:document.getElementById('draft-state').textContent,stale:window.__ffApp.draftStale,rev:window.__ffApp.draftRevision})));throw e;});
 check('Desired home loads matching 60 × 55 ft east-facing settings and all authored rooms',await page.evaluate(()=>document.getElementById('width').value==='60'&&document.getElementById('depth').value==='55'&&document.getElementById('facing').value==='90'&&window.__ffApp.planEditor.plan.floors[0].rooms.length===18));
 const hash=await page.evaluate(()=>window.__ff.scene.planHash);
 await page.locator('.project-workspace [data-project-view="specs"]').click();
 check('Specifications include care room, exact room sizes and provisional rear setback',(await page.locator('#project-specs-content').innerText()).includes('6.79 × 4.15')&&(await page.locator('#project-specs-content').innerText()).includes('subject to local approval'));
 await page.screenshot({path:out+'/specifications.png'});
 await page.locator('#project-specs-dialog [data-project-view="editor"]').click();
 check('Room editor opens the exact geometry without re-packing',await page.evaluate(()=>document.getElementById('plan-dialog').open&&window.__ffApp.planEditor.plan.floors[0].rooms.length===18&&!window.__ffApp.roomBoard.active));
 check('Editor accepts the service wing, bedroom ensuite and half counter',await page.evaluate(()=>!window.__ffApp.planEditor.localIssues().length));
 await page.screenshot({path:out+'/ground-editor.png'});await page.click('[data-close="plan-dialog"]');
 await page.locator('.project-workspace [data-project-view="cells"]').click();
 check('Matching ground-floor cell overview has sixteen cells and kitchen at front-left',await page.locator('#grid-board button').count()===16&&(await page.locator('#grid-board').innerText()).includes('Kitchen'));
 await page.screenshot({path:out+'/cell-guide.png'});await page.click('[data-close="grid-dialog"]');
 await page.locator('.project-workspace [data-project-view="2d"]').click();await page.locator('#drawing-image').waitFor();
 check('Dimensioned ground and first floor drawing sheets are available',await page.locator('#sheet-select option[value="A-101"]').count()===1&&await page.locator('#sheet-select option[value="A-102"]').count()===1);
 await page.screenshot({path:out+'/ground-2d.png'});
 await page.locator('.project-workspace [data-project-view="3d"]').click();
 await page.evaluate(()=>{window.__ff.viewer.setFloor(0);window.__ff.viewer.setMode('dollhouse');});await page.waitForTimeout(800);await page.locator('#scene').screenshot({path:out+'/ground-3d.png'});
 await page.evaluate(()=>window.__ff.viewer.setFloor(1));
 check('First-floor cutaway reveals lower furniture through the guarded living void',await page.evaluate(()=>{const v=window.__ff.viewer;return v.data.rooms.some(r=>r.id==='u-living-void'&&r.kind==='void')&&v.meshes.some(m=>m.visible&&m.userData.bucket.floor===0&&m.userData.bucket.roles.includes('furniture'));}));
 check('Saved editor retains the open atrium and full-height stair opening',await page.evaluate(()=>{const fs=window.__ffApp.planEditor.plan.floors;return fs[1].rooms.some(r=>r.id==='u-living-void'&&r.openToBelow)&&fs[0].openings.some(o=>o.id==='g-living-stair'&&o.width===3900&&o.height===3000);}));
 await page.waitForTimeout(600);await page.locator('#scene').screenshot({path:out+'/first-3d.png'});
 check('Single recliner, three right-side chairs, equipment table, corner cupboard and TV are individually editable',await page.evaluate(()=>window.__ff.scene.editables.filter(e=>e.roomId==='g-care').length===7));
 // Walk through the rendered model, including the new low partition and entrance steps.
 await page.evaluate(()=>{const v=window.__ff.viewer;v.paused=true;v.setMode('walk');});
 const spawnAt=async(x,y)=>page.evaluate(({x,y})=>{const v=window.__ff.viewer,w=v.walker;w.teleport(w.position.clone().set(x,0,-y));},{x,y});
 const walkTo=async(x,y)=>page.evaluate(({x,y})=>{const v=window.__ff.viewer,w=v.walker;let reached=false;for(let i=0;i<600;i++){const dx=x-w.position.x,dz=-y-w.position.z;if(Math.hypot(dx,dz)<.06){reached=true;break;}w.yaw=Math.atan2(-dx,-dz);w.update(1/60,{forward:1,strafe:0});}for(let i=0;i<20;i++)w.update(1/60,{forward:0,strafe:0});return {reached,position:w.position.toArray()};},{x,y});
 const openDoor=async id=>page.evaluate(id=>{const v=window.__ff.viewer,d=v.openings.items.find(o=>o.id===id);d.goal=1;for(let i=0;i<90;i++)v.openings.update(1/60);return d.value===1;},id);
 const gate=await page.evaluate(()=>{const g=window.__ff.scene.gate_model.find(g=>g.id==='exterior-vehicle-gate');return {x:g.start[0]+g.width/2,y:g.start[1]};});
 await spawnAt(gate.x,gate.y-.95);let gateWalk=await walkTo(gate.x,gate.y+.9);
 check('Closed main gate blocks passage',!gateWalk.reached);
 await spawnAt(gate.x,gate.y-.95);await page.evaluate(()=>{const v=window.__ff.viewer;v.walker.yaw=0;v.walker.pitch=0;v.canvas.focus();v.openings.updateTarget();});
 check('Main gate shows its open prompt from the street',await page.evaluate(()=>window.__ff.viewer.openings.prompt()?.text==='Open main vehicle gate'));
 await page.keyboard.press('f');await page.evaluate(()=>{for(let i=0;i<90;i++)window.__ff.viewer.openings.update(1/60);});
 check('F opens both main gate panels',await page.evaluate(()=>window.__ff.viewer.openings.items.find(d=>d.id==='exterior-vehicle-gate').value===1));
 gateWalk=await walkTo(gate.x,gate.y+1.95);check('Open main gate allows walking into the parking court',gateWalk.reached);
 await page.evaluate(()=>{const v=window.__ff.viewer;v.walker.yaw=Math.PI;v.walker.pitch=0;v.openings.updateTarget();});
 check('Main gate shows its close prompt from inside',await page.evaluate(()=>window.__ff.viewer.openings.prompt()?.text==='Close main vehicle gate'));
 await page.keyboard.press('f');await page.evaluate(()=>{for(let i=0;i<90;i++)window.__ff.viewer.openings.update(1/60);});
 check('F closes the main gate from inside',await page.evaluate(()=>window.__ff.viewer.openings.items.find(d=>d.id==='exterior-vehicle-gate').value===0));
 const parkingRoute=[];for(const [x,y] of [[16.3,.05],[15.7,.2],[15.7,4.95],[16.4,5.25]])parkingRoute.push(await walkTo(x,y));check('Parked car leaves a clear walking route from gate to veranda',parkingRoute.every(r=>r.reached));
 check('Upper lobby window and parked car appear in the saved scene',await page.evaluate(()=>window.__ff.scene.nodes.some(n=>n.owner==='parked-car')&&window.__ff.scene.opening_model.openings.some(o=>o.id==='u-lobby-east-window'&&o.width===2200)));
 await page.locator('#toggle-car').click();
 check('One click hides car geometry and removes its collision',await page.evaluate(()=>{const v=window.__ff.viewer;return !v.carVisible&&v.vehicle.meshes.every(m=>!m.visible)&&v.walker.optionalBVHs.length===0;}));
 await spawnAt(17.03,1.0);const emptyParking=await walkTo(17.03,4.6);check('Hidden car leaves the full parking bay walkable',emptyParking.reached);
 await spawnAt(16.0,5.1);await page.locator('#toggle-car').click();
 check('One click restores Kylaq and its collision',await page.evaluate(()=>{const v=window.__ff.viewer;return v.carVisible&&v.vehicle.meshes.every(m=>m.visible)&&v.walker.optionalBVHs.length===1;}));
 await spawnAt(10.2,1.4);await openDoor('g-dining-east');let walked=await walkTo(10.2,-1.6);console.log('Dining exit',walked);check('New dining door and steps allow a real walk to the tiled court',walked.reached&&walked.position[1]<-.3);
 walked=await walkTo(10.2,1.1);check('Dining entrance steps allow the return indoors',walked.reached&&Math.abs(walked.position[1])<.1);
 await spawnAt(4.75,11.1);await openDoor('g-bath-door');walked=await walkTo(4.75,12.3);console.log('Rear bathroom entry',walked);check('Bedroom ensuite can be entered standing',walked.reached&&Math.abs(walked.position[1])<.1);
 walked=await walkTo(4.75,11.1);check('Bedroom ensuite exit remains clear',walked.reached);
 await spawnAt(8.45,2.8);const kitchenRoute=[];for(const [x,y] of [[7.14,2.8],[7.14,2.3],[6.6,2.3]])kitchenRoute.push(await walkTo(x,y));console.log('Kitchen entry passage',kitchenRoute);check('Hall opening leads into kitchen clear of serving counter and rear storage',kitchenRoute.every(r=>r.reached));
 await spawnAt(3.9,4.15);for(let floor=0;floor<2;floor++){const positions=[];for(const [x,y] of [[.73,4.15],[.73,5.45],[3.9,5.45],[3.9,4.15]])positions.push(await walkTo(x,y));console.log('Stair floor',floor,positions);check(`Open stair preserves the climb from floor ${floor} to ${floor+1}`,positions.every(r=>r.reached)&&Math.abs(positions.at(-1).position[1]-(floor+1)*3.15)<.1);}
 await spawnAt(13.9,9.2);await openDoor('g-care-veranda');walked=await walkTo(13.9,7.2);check('Open sliding glass leads to the level clear veranda',walked.reached&&Math.abs(walked.position[1])<.1);
 walked=await walkTo(13.9,9.2);check('Veranda route works in both directions',walked.reached);
 await spawnAt(9.8,9.4);await openDoor('g-care-living');walked=await walkTo(9.8,7.9);console.log('Living glass',walked);check('Wide living glass connects directly to the care room',walked.reached);
 await spawnAt(10.7,7.7);await openDoor('g-living-veranda');walked=await walkTo(12.4,7.7);check('Living hall has its own direct sliding-glass route to veranda',walked.reached);
 await spawnAt(10.3,5.0);walked=await walkTo(11.6,5.0);check('Restored drawing-room wall physically separates it from living',!walked.reached);
 await spawnAt(13.15,5.1);await openDoor('g-drawing-veranda');walked=await walkTo(13.15,6.4);check('Drawing room has a separate door to the veranda',walked.reached);
 await spawnAt(9.1,11.7);await openDoor('g-care-caregiver');walked=await walkTo(7.8,11.7);check('Caregiver bedroom is reached behind the recliner',walked.reached);
 await openDoor('g-caregiver-garden-door');const gardenRoute=[];for(const [x,y]of [[7.8,13.65],[9.2,13.65],[15.98,13.45],[15.98,10.1],[15.98,9.0],[16.1,6.2],[16.1,5.15]])gardenRoute.push(await walkTo(x,y));console.log('Independent rear exit',gardenRoute);check('Caregiver can walk via rear garden and veranda to outside without the ICU',gardenRoute.every(r=>r.reached));
 await page.evaluate(()=>{const v=window.__ff.viewer;v.openings.items.find(o=>o.id==='g-care-caregiver').goal=0;for(let i=0;i<90;i++)v.openings.update(1/60);});await spawnAt(7.35,11.5);await openDoor('g-caregiver-toilet');walked=await walkTo(7.35,10.45);check('Rear caregiver attached toilet is accessible',walked.reached);
 await spawnAt(5.1,7.05);await openDoor('g-bedroom-door');walked=await walkTo(5.1,9.1);check('Bedroom entrance faces the stair-side hall',walked.reached);
 await spawnAt(6.55,7.8);walked=await walkTo(6.55,8.95);check('Plain living-hall wall prevents entry into the ventilation lightwell',!walked.reached);
 check('Removed lightwell door has no interactive panel',await page.evaluate(()=>!__ff.viewer.openings.items.some(o=>o.id==='g-living-garden-door')));
 check('Former caregiver footprint has real lawn grass and planted pots',await page.evaluate(()=>__ff.scene.lawns.some(l=>l.id==='g-care-lawn/grass')&&__ff.scene.nodes.some(n=>n.id==='g-care-lawn/clear-path')));
 await page.evaluate(()=>{const v=window.__ff.viewer,d=v.openings.items.find(o=>o.id==='g-dining-east');d.goal=0;for(let i=0;i<90;i++)v.openings.update(1/60);});
 await spawnAt(10.3,.7);await openDoor('g-dining-drawing');walked=await walkTo(11.6,.7);check('Separate drawing room connects through the small dining door',walked.reached);
 await spawnAt(4.2,1.6);await openDoor('g-kitchen-south');await spawnAt(3.60,.90);walked=await walkTo(2.4,.90);check('Kitchen pantry is reachable from the kitchen',walked.reached);
 await spawnAt(4.2,2.0);await openDoor('g-kitchen-wash');await spawnAt(3.60,3.12);walked=await walkTo(2.724,3.12);check('Open wash yard is reachable from the kitchen',walked.reached);
 await page.evaluate(()=>{const v=window.__ff.viewer;v.setMode('solid');v.paused=false;});
 check('View switching preserves the generated plan hash and input mode',await page.evaluate(h=>window.__ff.scene.planHash===h&&!window.__ffApp.draftStale&&document.getElementById('plan-mode').value==='custom',hash));
 await page.selectOption('#workspace-project','current-project');await page.waitForFunction(id=>window.__ff.buildId===id,original.build,{timeout:180000,polling:100});
 check('Current project can be restored from the saved project switcher',await page.evaluate(p=>window.__ffApp.collect().brief.title===p.brief.title,original.project));
 await page.selectOption('#workspace-project','working:my-desired-home');await page.waitForFunction(()=>window.__ff.buildId==='sample:my-desired-home',null,{timeout:180000,polling:100});
 await page.reload();await page.waitForFunction(()=>document.getElementById('workspace-project')?.value==='working:my-desired-home'&&window.__ffApp?.viewer,null,{timeout:180000,polling:100});
 check('Desired home and project switcher survive refresh',await page.evaluate(h=>window.__ff.scene.planHash===h&&!window.__ffApp.draftStale,hash));
 await page.evaluate(()=>{window.__ff.viewer.setMode('solid');window.__ff.viewer.setView('hero');});await page.waitForTimeout(800);await page.locator('#scene').screenshot({path:out+'/exterior.png'});
 await page.setViewportSize({width:390,height:844});check('Project navigation wraps on a phone',await page.locator('.project-workspace').evaluate(e=>e.scrollWidth<=e.clientWidth+1));
 check('No browser errors',errors.length===0);writeFileSync(out+'/checks.json',JSON.stringify({checks,errors},null,2));
}finally{await browser?.close();server.kill('SIGINT');}
