import {writeFileSync} from 'node:fs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const checks=[],errors=[];const check=(name,pass)=>{checks.push({name,pass:!!pass});console.log(pass?'PASS':'FAIL',name);if(!pass)throw Error(name);};
try {
 const p=await browser.newPage({viewport:{width:1500,height:1000}});p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://127.0.0.1:8765/samples/my-desired-home/preview.html');await p.waitForFunction(()=>window.__ff?.ready,null,{timeout:180000});
 const ids=['g-care-veranda/panel-b','g-care-veranda/panel-c'];
 check('B and C are independently operable sliding doors',await p.evaluate(ids=>ids.every(id=>{const d=__ff.viewer.openings.items.find(o=>o.id===id);return d&&d.value===0&&d.parts.length===1&&d.parts[0].slide&&d.handle;}),ids));
 check('D has no opening interaction',await p.evaluate(()=>!__ff.viewer.openings.items.some(o=>o.id==='g-care-lawn-window')));
 const spawn=async(x,y)=>p.evaluate(({x,y})=>{const v=__ff.viewer;v.setMode('walk');v.paused=true;v.walker.teleport(v.walker.position.clone().set(x,0,-y));},{x,y});
 const door=async(id,goal)=>p.evaluate(({id,goal})=>{const v=__ff.viewer,d=v.openings.items.find(o=>o.id===id);d.goal=goal;for(let i=0;i<100;i++)v.openings.update(1/60);return d.value===goal;},{id,goal});
 const walk=async(x,y)=>p.evaluate(({x,y})=>{const w=__ff.viewer.walker;for(let i=0;i<600;i++){const dx=x-w.position.x,dz=-y-w.position.z;if(Math.hypot(dx,dz)<.06)return true;w.yaw=Math.atan2(-dx,-dz);w.update(1/60,{forward:1,strafe:0});}return false;},{x,y});
 const shot=async(name,eye,target)=>{await p.evaluate(({eye,target})=>{const v=__ff.viewer;v.setMode('walk');v.paused=true;v.fitHeld=null;v.zoomAnim=null;v.walker.teleport(v.walker.position.clone().set(eye[0],0,eye[2]));v.camera.fov=78;v.camera.updateProjectionMatrix();v.camera.position.set(...eye);v.camera.lookAt(...target);for(let i=0;i<100;i++)v.adapt(.05);v.updateProbe();for(let i=0;i<100;i++)v.adapt(.05);v.hud.show(false);v.updateLights();v.vegetation?.update(v.time,v.camera);v.composer.render(.016);},{eye,target});await p.waitForTimeout(300);const bytes=await p.evaluate(async()=>Array.from(new Uint8Array(await(await __ff.viewer.snapshot({width:1600})).arrayBuffer())));writeFileSync(`evidence/desired-home/${name}.png`,Buffer.from(bytes));};
 await shot('icu-corner-closed',[11.65,1.65,-11.1],[14.8,1.2,-8.75]);
 await spawn(13.4,9.25);check('Closed B blocks passage',!await walk(13.4,7.7));
 await spawn(14.55,9.25);check('Closed C blocks passage',!await walk(14.55,7.7));
 await spawn(14,10);check('B opens',await door(ids[0],1));
 check('C remains closed',await p.evaluate(id=>__ff.viewer.openings.items.find(o=>o.id===id).value===0,ids[1]));
 await spawn(13.4,9.25);check('B alone clears its doorway',await walk(13.4,7.7));
 await spawn(14.55,9.25);check('C still blocks its doorway',!await walk(14.55,7.7));
 await spawn(14,10);await door(ids[0],0);check('C opens independently',await door(ids[1],1));
 await spawn(14.55,9.25);check('C alone clears its doorway',await walk(14.55,7.7));
 await spawn(14,10);await door(ids[0],1);
 await shot('icu-corner-open',[11.65,1.65,-11.1],[14.8,1.2,-8.75]);
 check('Both open handles remain targetable',await p.evaluate(ids=>{const v=__ff.viewer;return ids.every(id=>{const d=v.openings.items.find(o=>o.id===id);const h=d.handle.clone().applyMatrix4(d.parts[0].group.matrixWorld),eye=h.clone();eye.y=1.63;eye.z=-9.3;v.walker.position.set(eye.x,0,eye.z);return v.openings.findTarget(eye,h.clone().sub(eye).normalize())?.id===id;});},ids));
 await spawn(12.1,9.2);check('New solid wall A blocks passage',!await walk(12.1,7.7));
 await spawn(14.65,9.2);check('Fixed pane D blocks passage',!await walk(16,9.2));
 await spawn(14,10);for(const id of ids)check(id+' closes',await door(id,0));
 await spawn(13.4,9.25);check('Reclosed B blocks passage',!await walk(13.4,7.7));
 await spawn(14.55,9.25);check('Reclosed C blocks passage',!await walk(14.55,7.7));
 check('No browser errors',!errors.length);
} finally {writeFileSync('evidence/desired-home/icu-corner-checks.json',JSON.stringify({checks,errors},null,2));await browser.close();}
