/* Optional adapter. Direct versions pinned; installation/GPU verification required. */
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {RGBELoader} from 'three/addons/loaders/RGBELoader.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {WebGLPathTracer} from 'three-gpu-pathtracer';
import {gsap} from 'gsap';
const $=id=>document.getElementById(id),status=t=>$('status').textContent=t;
const renderer=new THREE.WebGLRenderer({canvas:$('view'),antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color('#e4e8df');let envTarget,pmrem=new THREE.PMREMGenerator(renderer);envTarget=pmrem.fromScene(new RoomEnvironment(),.04);scene.environment=envTarget.texture;
const camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,.05,500);camera.position.set(18,10,22);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(5,2,-5);controls.enableDamping=!matchMedia('(prefers-reduced-motion: reduce)').matches;
const sun=new THREE.DirectionalLight(0xfff3de,2.5);sun.position.set(-14,20,9);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-25,right:25,top:25,bottom:-25,near:.1,far:100});scene.add(sun);scene.add(new THREE.HemisphereLight(0xffffff,0x727e65,.3));
let model=null,pathTracer=null,tracing=false,roof=true,disposed=false,frame,originalSize=null;
function disposeModel(){if(!model)return;let geos=new Set(),mats=new Set();model.traverse(o=>{if(o.geometry)geos.add(o.geometry);if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>mats.add(m));});for(let g of geos)g.dispose();for(let m of mats)m.dispose();scene.remove(model);model=null;}
async function loadBuffer(buffer){tracing=false;disposeModel();const gltf=await new GLTFLoader().parseAsync(buffer,'');model=gltf.scene;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});scene.add(model);const box=new THREE.Box3().setFromObject(model),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),r=Math.max(size.x,size.y,size.z);controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(r*.72,r*.48,r*.95));controls.update();if(pathTracer){pathTracer.setScene(scene,camera);pathTracer.reset();}status('GLB loaded. Preliminary geometry; raster view. Add a licensed HDRI for stronger illumination.');}
$('glb').onchange=async e=>{try{await loadBuffer(await e.target.files[0].arrayBuffer());}catch(err){status(err.message);}};
$('hdri').onchange=async e=>{let file=e.target.files[0];if(!file)return;let u=URL.createObjectURL(file);try{let hdr=await new RGBELoader().setDataType(THREE.FloatType).loadAsync(u);let values=hdr.image.data,sum=0,count=0;for(let i=0;i<values.length;i+=4){sum+=.2126*values[i]+.7152*values[i+1]+.0722*values[i+2];count++;}let factor=.22/Math.max(sum/count,1e-6);for(let i=0;i<values.length;i+=4)for(let c=0;c<3;c++)values[i+c]*=factor;hdr.needsUpdate=true;hdr.mapping=THREE.EquirectangularReflectionMapping;envTarget?.dispose();envTarget=pmrem.fromEquirectangular(hdr);scene.environment=envTarget.texture;hdr.dispose();if(pathTracer){pathTracer.setScene(scene,camera);pathTracer.reset();}status('HDRI mean luminance normalised to 0.22; background stays neutral. Record your HDRI licence separately.');}catch(err){status(err.message);}finally{URL.revokeObjectURL(u);}};
$('trace').onclick=()=>{try{if(!model)throw Error('Load a generated GLB first.');if(!pathTracer)pathTracer=new WebGLPathTracer(renderer);let width=Number($('resolution').value);originalSize=[innerWidth,innerHeight];renderer.setPixelRatio(1);renderer.setSize(width,Math.round(width*9/16),false);camera.aspect=16/9;camera.updateProjectionMatrix();pathTracer.setScene(scene,camera);pathTracer.reset();tracing=true;status('Path tracing; stop at any time. 128 samples target. Runtime depends on your GPU.');}catch(e){tracing=false;status('Path tracer unavailable: '+e.message+' Raster view remains available.');}};
$('stop').onclick=()=>{tracing=false;status('Accumulation stopped. Capture the result before resizing.');};$('capture').onclick=()=>renderer.domElement.toBlob(blob=>{let u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=tracing?'FloorForge-path-traced-study.png':'FloorForge-view.png';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});$('roof').onclick=()=>{roof=!roof;model?.traverse(o=>{if(o.userData.role==='roof'||o.name==='roof-slab')o.visible=roof;});if(pathTracer){pathTracer.setScene(scene,camera);pathTracer.reset();}};
controls.addEventListener('change',()=>{if(pathTracer&&tracing){pathTracer.updateCamera();pathTracer.reset();}});
function tick(){if(disposed)return;controls.update();if(tracing){pathTracer.renderSample();status('Path traced samples: '+Math.floor(pathTracer.samples)+' / 128 · preliminary geometry');if(pathTracer.samples>=128)tracing=false;}else if(!pathTracer||!originalSize)renderer.render(scene,camera);frame=requestAnimationFrame(tick);}tick();
addEventListener('resize',()=>{originalSize=null;tracing=false;renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();});
if(!matchMedia('(prefers-reduced-motion: reduce)').matches)gsap.from(document.querySelector('header'),{y:-10,opacity:0,duration:.45,ease:'power2.out'});
addEventListener('pagehide',()=>{disposed=true;cancelAnimationFrame(frame);controls.dispose();disposeModel();pathTracer?.dispose();envTarget?.dispose();pmrem.dispose();renderer.dispose();},{once:true});
const build=new URLSearchParams(location.search).get('build');if(build&&/^[0-9a-f]{24}$/.test(build)){fetch('/builds/'+build+'/model.glb').then(r=>{if(!r.ok)throw Error('Build not found');return r.arrayBuffer();}).then(loadBuffer).catch(e=>status(e.message));}
