/* FloorForge local studio. All geometry is supplied by the Python engine. */
'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let session,viewer,currentProject={brief:{}},activeBuild='demo',base='/demo/',currentScene,currentBuilding,currentReport,metadata,unit='ft',generationBusy=false,gridRows=Array.from({length:12},()=>Array(9).fill('')),savedImages=[],proposed=null,styleValue='warm',exteriorThemeValue='modern_tropical',interiorThemeValue='bright_natural',pendingThemeSnapshot=null,sheetObjectURL=null;
const FRONTEND_BUILD_ID='ff-realistic-walkthrough-20260926-v4';
let backendBuildId='pending';
const PRESETS={villa:{title:'The Verandah House',width_mm:12192,depth_mm:18288,bedrooms:3,storeys:2,budget_lakh:65,front_mm:3300,rear_mm:1200,left_mm:1100,right_mm:1100},compact:{title:'The Garden Pavilion',width_mm:9144,depth_mm:12192,bedrooms:2,storeys:1,budget_lakh:25,front_mm:1800,rear_mm:900,left_mm:750,right_mm:750},small:{title:'The Quiet First Home',width_mm:7620,depth_mm:10668,bedrooms:1,storeys:1,budget_lakh:18,front_mm:1200,rear_mm:600,left_mm:450,right_mm:450}};
const ADVANCED=[
['Site & setbacks',[['title','Project name','text'],['front_mm','Front open space / mm','number'],['rear_mm','Rear open space / mm','number'],['left_mm','Left open space / mm','number'],['right_mm','Right open space / mm','number'],['latitude','Latitude','number'],['longitude','Longitude','number'],['timezone_hours','UTC offset / hours','number'],['solar_date','Solar-study date','date'],['solar_hour','Solar-study local hour','number']]],
['Structure & levels',[['plinth_mm','Floor above reference ground / mm','number'],['floor_height_mm','Floor-to-floor / mm','number'],['soil','Soil context (not bearing capacity)',['unknown','black-cotton','rocky','sandy','alluvial','red-laterite','murrum']]]],
['Programme & character',[['open_kitchen','Open kitchen connection','checkbox'],['parking','Parking court (needs 5.5 m front depth)','checkbox'],['pooja','Pooja niche','checkbox'],['eldercare','Preserve eldercare request; specialist design remains open','checkbox'],['variant','Plan variant',['0','1','2']],['vastu','Vastu preference (advisory)',['off','flexible','moderate','strict']]]],
['Finish & cost scenarios',[['finish','Finish context',['economy','standard','premium']],['rate_low_inr_ft2','Illustrative low rate / ₹ per ft²','number'],['rate_high_inr_ft2','Illustrative high rate / ₹ per ft²','number'],['cost_contingency_pct','Contingency scenario / %','number']]]
];
function toast(message,ms=8500){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,ms);}
async function fetchJSON(url,body){let response=await fetch(url,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-FloorForge-Token':session.token},body:JSON.stringify(body)});let data=await response.json();if(!response.ok){let error=new Error(data.message||data.error||'Request failed');error.data=data;throw error;}return data;}
function status(t){$('status').textContent=t;}
function download(blob,name){let u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);}
function initAdvanced(){let root=$('advanced-fields');root.replaceChildren();for(let [name,fields]of ADVANCED){let details=document.createElement('details'),summary=document.createElement('summary');summary.textContent=name;details.append(summary);for(let [key,label,type]of fields){let lab=document.createElement('label');lab.textContent=label;let el;if(Array.isArray(type)){el=document.createElement('select');for(let option of type){let opt=document.createElement('option');opt.value=option;opt.textContent=key==='variant'?{'0':'Public hub','1':'Mirrored hub','2':'Shorter footprint'}[option]:option;el.append(opt);}}else{el=document.createElement('input');el.type=type;if(type==='number')el.step='any';if(type==='checkbox'){lab.classList.add('check');lab.textContent='';lab.append(el,document.createTextNode(label));}}el.id='adv-'+key;el.dataset.key=key;if(type!=='checkbox')lab.append(el);details.append(lab);}root.append(details);}}
function setValues(v){$('width').value=(v.width_mm/(unit==='ft'?304.8:1000)).toFixed(2);$('depth').value=(v.depth_mm/(unit==='ft'?304.8:1000)).toFixed(2);$('facing').value=v.road_bearing_deg;$('bedrooms').value=v.bedrooms;$('storeys').value=v.storeys;$('budget').value=v.budget_lakh;styleValue=v.style||'warm';exteriorThemeValue=v.exterior_theme??session.defaults.exterior_theme??'modern_tropical';interiorThemeValue=v.interior_theme??session.defaults.interior_theme??'bright_natural';for(let [,fields]of ADVANCED)for(let [key,,type]of fields){let el=$('adv-'+key);if(type==='checkbox')el.checked=Boolean(v[key]);else el.value=v[key]??session.defaults[key];}renderStyles();renderThemes();}
function collect(){let values={...session.defaults,...currentProject.brief};for(let [,fields]of ADVANCED)for(let [key,,type]of fields){let el=$('adv-'+key);values[key]=type==='checkbox'?el.checked:type==='number'||key==='variant'?Number(el.value):el.value;}Object.assign(values,{width_mm:Math.round(Number($('width').value)*(unit==='ft'?304.8:1000)),depth_mm:Math.round(Number($('depth').value)*(unit==='ft'?304.8:1000)),road_bearing_deg:Number($('facing').value),bedrooms:Number($('bedrooms').value),storeys:Number($('storeys').value),budget_lakh:Number($('budget').value),style:styleValue,exterior_theme:exteriorThemeValue,interior_theme:interiorThemeValue,change_policy:'exterior_refinement',interior_layout_locked:true,theme_version:'1'});let p={...currentProject,schema:'floorforge.project/0.3',brief:values};p.sources=(p.sources||[]).filter(s=>s.id!=='unused-description');let text=$('description').value.trim();if($('text-used').checked)p.text=text;else{p.text='';if(text)p.sources.push({id:'unused-description',kind:'text',values:{},raw_text:text,enabled:false});}p.attachments=savedImages.map(({file,objectURL,...meta})=>meta);if($('grid-used').checked)p.grid={cell_mm:Number($('grid-cell').value),floors:[gridRows]};else delete p.grid;return p;}
function renderStyles(){if(!session)return;$('styles').replaceChildren();for(let [key,s]of Object.entries(session.styles)){let b=document.createElement('button');b.className='style-card'+(styleValue===key?' active':'');b.dataset.style=key;b.setAttribute('aria-pressed',String(styleValue===key));b.title=s.signature;b.innerHTML=`<span class="swatches"><span style="background:${s.wall}"></span><span style="background:${s.accent}"></span><span style="background:${s.wood}"></span></span>${esc(s.label)}`;b.onclick=()=>{styleValue=key;renderStyles();status('Style selected. Regenerate to apply it to geometry and exports.');};$('styles').append(b);}}
function renderThemes(){if(!session?.themes)return;for(let [kind,selected] of [['exterior',exteriorThemeValue],['interior',interiorThemeValue]]){let root=$(kind+'-themes');if(!root)continue;root.replaceChildren();for(let item of session.themes[kind]||[]){let b=document.createElement('button');b.type='button';b.className='theme-card'+(selected===item.id?' active':'');b.setAttribute('aria-pressed',String(selected===item.id));b.title=item.description;b.innerHTML=`<strong>${esc(item.label)}</strong><span>${esc(item.description)}</span>`;b.onclick=()=>previewTheme(kind,item.id);root.append(b);}}let ext=session.themes.exterior.find(x=>x.id===exteriorThemeValue),inside=session.themes.interior.find(x=>x.id===interiorThemeValue);$('theme-impact').textContent=`${ext?.label||'Exterior'}: real porch, balcony, opening and landscape geometry. ${inside?.label||'Interior'}: finishes change while the room layout stays locked.`;}
function previewTheme(kind,key){if((kind==='exterior'?exteriorThemeValue:interiorThemeValue)===key)return;if(!pendingThemeSnapshot)pendingThemeSnapshot={exterior:exteriorThemeValue,interior:interiorThemeValue};if(kind==='exterior')exteriorThemeValue=key;else interiorThemeValue=key;renderThemes();let ext=session.themes.exterior.find(x=>x.id===exteriorThemeValue),inside=session.themes.interior.find(x=>x.id===interiorThemeValue);$('theme-dialog-title').textContent=`Preview ${ext.label} + ${inside.label}`;$('theme-dialog-content').innerHTML=`<p>${esc(ext.description)}</p><p>${esc(inside.description)}</p><p class="notice">Apply keeps the interior room cells, stairs and furniture layout protected. Generate will update the shared scene, drawings and export package together.</p>`;$('theme-dialog').showModal();}
function applyThemeSelection(){pendingThemeSnapshot=null;$('theme-dialog').close();status('Design language applied. Generate to preview the coordinated exterior.');}
function revertThemeSelection(){if(pendingThemeSnapshot){exteriorThemeValue=pendingThemeSnapshot.exterior;interiorThemeValue=pendingThemeSnapshot.interior;}pendingThemeSnapshot=null;renderThemes();$('theme-dialog').close();status('Design language reverted.');}
async function applyProject(p){let intent=await fetchJSON('/api/intent',p);currentProject=p;setValues(intent.values);$('description').value=p.text||p.sources?.find(s=>s.id==='unused-description')?.raw_text||'';$('text-used').checked=!p.sources?.some(s=>s.id==='unused-description');gridRows=p.grid?.floors?.[0]||Array.from({length:12},()=>Array(9).fill(''));$('grid-used').checked=Boolean(p.grid);$('grid-cell').value=p.grid?.cell_mm||1000;savedImages=(p.attachments||[]).map(x=>({...x}));renderReferences();renderSources();renderGrid();}
function renderSources(){$('loaded-sources').replaceChildren();for(let s of currentProject.sources||[]){let lab=document.createElement('label');lab.className='check';let box=document.createElement('input');box.type='checkbox';box.checked=s.enabled!==false;box.onchange=()=>{s.enabled=box.checked;};lab.append(box,document.createTextNode(`${s.id} · ${s.kind}`));$('loaded-sources').append(lab);}}
async function understood(){try{let p=collect(),intent=await fetchJSON('/api/intent',p);let keys=['width_mm','depth_mm','road_bearing_deg','bedrooms','storeys','budget_lakh','style','exterior_theme','interior_theme','open_kitchen','parking','vastu'];$('intent-content').innerHTML=`<table class="review-table"><tr><th>FIELD</th><th>UNDERSTOOD</th><th>FROM</th></tr>${keys.map(k=>`<tr><td>${esc(k.replaceAll('_',' '))}</td><td>${esc(intent.values[k])}</td><td>${esc(intent.provenance[k].selected.join(', '))}</td></tr>`).join('')}</table><h4 style="margin-top:20px">Preserved inputs</h4><p>${intent.sources.map(s=>esc(s.id)+' ('+(s.enabled===false?'Off':'Used')+')').join(' · ')}</p>${intent.notices.map(n=>`<p class="notice">${esc(n)}</p>`).join('')}`;$('intent-dialog').showModal();}catch(e){toast(formatError(e));}}
function formatError(e){let d=e.data?.details;if(d?.errors)return e.message+'\n'+d.errors.slice(0,3).map(x=>x.code+' '+(x.id||'')).join('\n');return e.message;}
async function generate(){if(generationBusy)return;let p=collect();generationBusy=true;$('generate').disabled=true;$('progress').hidden=false;$('progress-fill').style.width='5%';$('intent-dialog').close();status('Reading your brief…');try{let job=await fetchJSON('/api/generate',p);for(;;){await new Promise(r=>setTimeout(r,550));let state=await fetchJSON('/api/jobs/'+job.job_id);let events=state.events||[],last=events.at(-1);if(last){status(last.stage+' · '+last.status);let done=events.filter(x=>x.status!=='running').length;$('progress-fill').style.width=Math.min(94,8+done*7.5)+'%';}if(state.status==='error'){let e=new Error(state.error.message);e.data=state.error;throw e;}if(state.status==='done'){currentProject=p;await loadBuild(state.result.id);$('progress-fill').style.width='100%';toast('Your design and export package are ready for preliminary review.',4000);break;}}}catch(e){toast(formatError(e),12000);status('Design not published · '+e.message);}finally{generationBusy=false;$('generate').disabled=false;setTimeout(()=>$('progress').hidden=true,600);}}
async function loadBuild(id){base=id==='demo'?'/demo/':'/builds/'+id+'/';activeBuild=id;const [sc,b,r,sheets]=await Promise.all(['scene.json','building.json','report.json','sheets.json'].map(n=>fetchJSON(base+n)));currentScene=sc;currentBuilding=b;currentReport=r;metadata=sheets;if(b.exterior){exteriorThemeValue=b.exterior.theme||'current';interiorThemeValue=b.exterior.interior_theme||'current';renderThemes();}$('loading').hidden=true;$('project-title').textContent=b.brief.title;$('build-id').textContent=id==='demo'?'BUNDLED EXAMPLE':id.slice(0,8).toUpperCase();$('project-meta').textContent=`${b.brief.bedrooms} bedroom${b.brief.bedrooms===1?'':'s'} · ${b.storeys===1?'Ground floor':'G+1'} · ${r.areas.gross_floor_m2.toFixed(0)} m² gross`;$('live-diagnostic').textContent=`TEMP LIVE DIAGNOSTIC · backend ${backendBuildId.slice(0,12)} · frontend ${FRONTEND_BUILD_ID} · build ${id==='demo'?'bundled':id} · scene ${sc.exterior_revision||'legacy'} · ${sc.schema}`;
try{if(!viewer){viewer=new FloorForgeViewer($('scene'),{onStatus:status,quality:$('quality').value||'auto'});viewer.onFloorChange=f=>{$('floor').value=String(f);};viewer.onModeChange=m=>setModeButtons(m);frameInsets();}viewer.setScene(sc);viewer.setGrade($('grade').value);document.querySelector('[data-view="balcony"]').hidden=!viewer.balcony();$('viewer-fallback').hidden=true;}catch(e){$('viewer-error').textContent=e.message;$('viewer-fallback').hidden=false;}
$('floor').innerHTML=Array.from({length:b.storeys},(_,i)=>`<option value="${i}">${i?'First floor':'Ground floor'}</option>`).join('');$('sheet-select').innerHTML=sheets.map(s=>`<option value="${esc(s.id)}">${esc(s.id+' / '+s.title)}</option>`).join('');$('pdf-link').href=base+'drawings.pdf';await showSheet();renderReport();renderExports();window.__ff={viewer,scene:sc,building:b,report:r,ready:true,buildId:id};status('Geometry screened · regulatory and structural approval remain open.');}
async function showSheet(){let id=$('sheet-select').value;if(!id)return;try{let response=await fetch(base+'sheets/'+id+'.svg');if(!response.ok)throw Error('Sheet unavailable');let blob=await response.blob();if(sheetObjectURL)URL.revokeObjectURL(sheetObjectURL);sheetObjectURL=URL.createObjectURL(blob);$('drawing-image').src=sheetObjectURL;}catch(e){toast(e.message);}}
function renderReport(){let r=currentReport;if(!r)return;let c=r.cost,e=r.exterior||{};$('review-content').innerHTML=`<div class="stats"><div class="stat"><span>GROSS FLOOR AREA</span><strong>${esc(r.areas.gross_floor_m2)} m²</strong><span>${esc(r.areas.gross_floor_ft2)} ft² · ${esc(r.areas.ground_coverage_pct)}% ground coverage</span></div><div class="stat"><span>ILLUSTRATIVE COST SCENARIO</span><strong>₹${esc(c.low_lakh)}–${esc(c.high_lakh)} L</strong><span>Editable assumed rates, not market quotations</span></div><div class="stat"><span>EXTERIOR STUDY</span><strong>${esc(e.theme_label||'Current')}</strong><span>${esc(e.assembly_count||0)} assemblies · ${esc(e.landscape_feature_count||0)} landscape features</span></div></div>${!c.within_budget_low?'<div class="notice">Even the low illustrative cost scenario exceeds your budget context. The design has not been declared affordable.</div>':''}<div class="notice">Regulatory: ${esc(r.review.regulatory)} · Structure: ${esc(r.review.structural)} · Accessibility: ${esc(r.review.accessibility)}. These are not approvals.</div><div class="review-card"><h4>What was checked</h4><p>${r.review.checks.map(esc).join(' · ')}</p>${r.review.warnings.map(w=>`<p><strong>${esc(w.code)}</strong> — ${esc(w.message)}</p>`).join('')}</div><div class="review-card"><h4>Space schedule</h4><table class="review-table"><tr><th>SPACE</th><th>FLOOR</th><th>CLEAR AREA</th></tr>${currentBuilding.spaces.map(s=>`<tr><td>${esc(s.name)}</td><td>${s.floor?'First':'Ground'}</td><td>${s.area_m2.toFixed(2)} m²</td></tr>`).join('')}</table></div><div class="review-card"><h4>Timeline scenario</h4><p>Illustrative sequencing, not a contractor commitment.</p>${r.timeline.map(t=>`<div class="timeline-row"><span>${esc(t.phase)}</span><div class="timeline-track"><span style="margin-left:${t.start_week/42*100}%;width:${t.duration_weeks/42*100}%"></span></div><span>${t.duration_weeks} weeks</span></div>`).join('')}</div><div class="review-card"><h4>Sun, soil & site</h4><p>Sun-study elevation ${r.solar.elevation_deg.toFixed(1)}°, azimuth ${r.solar.azimuth_deg.toFixed(1)}°. ${esc(r.solar.method)}. Warm/dusk buttons change the display grade, not the astronomical time.</p><p>${esc(r.structure.soil_warning)}</p><p>Surveyed boundaries, drainage levels, foundation design, loading, lateral stability and reinforcement remain outside this release.</p></div><div class="review-card"><h4>Cost basis & exclusions</h4><p>${esc(c.basis)} Rates: ₹${c.rates_inr_ft2.map(esc).join('–')}/ft², contingency ${esc(c.contingency_pct)}%.</p><p>Excludes ${c.excludes.map(esc).join(', ')}.</p></div><div class="review-card"><h4>Services & quantity truth</h4><p>${r.mep.notes.map(esc).join(' ')}</p><p>${esc(r.quantities.reason)}</p></div>`;}
function renderExports(){let items=[['FloorForge-export.zip','The entire package','All exported artifacts and their manifest'],['drawings.pdf','Drawing & review set','A3 plans, site, elevations, section and review pages'],['floorplans.dxf','Layered DXF floor plans','Re-import checked with ezdxf, not AutoCAD GUI'],['model.glb','3D model / GLB','Re-imported with Trimesh; metres, Y-up'],['model.ifc','IFC4 coordination model','STEP references checked; independent viewer gate open'],['project.floorforge.json','Reopenable project','Structured inputs, original text and reference metadata'],['scene.json','Editable scene contract','Shared meshes, placements, materials and visible-fixture lights'],['export-checks.json','Export verification','Machine-readable scope and checks'],['manifest.json','Build provenance','Kernel, input, dependency and artifact hashes']];$('export-list').innerHTML=items.map(([file,title,description])=>`<a class="export-item" href="${base+file}" download><strong>${esc(title)} ↗</strong><span>${esc(description)}</span></a>`).join('');}
function showTab(name){for(let b of document.querySelectorAll('[data-tab]')){b.classList.toggle('active',b.dataset.tab===name);b.setAttribute('aria-pressed',String(b.dataset.tab===name));}for(let n of ['home','drawings','documents','exports'])$(n+'-panel').hidden=n!==name;viewer&&(viewer.dirty=true);}
function renderGrid(){let cols=gridRows[0]?.length||9;$('grid-board').style.gridTemplateColumns=`repeat(${cols},1fr)`;$('grid-board').replaceChildren();let colors={living:'#cbd7bd',dining:'#dcd6b9',kitchen:'#bacdbd',hall:'#e6e5d6',bedroom:'#cec4b0',bathroom:'#b6cacc',utility:'#cad2c7',study:'#dbc8b5'};for(let y=gridRows.length-1;y>=0;y--)for(let x=0;x<cols;x++){let b=document.createElement('button');let value=gridRows[y][x];b.type='button';b.textContent=value||'';b.title=`Cell ${x},${y}: ${value||'outside'}`;b.style.background=colors[(value||'').split('-')[0]]||'#ebeee4';const paint=()=>{gridRows[y][x]=$('grid-brush').value;b.textContent=gridRows[y][x];b.style.background=colors[gridRows[y][x].split('-')[0]]||'#ebeee4';};b.onpointerdown=e=>{e.preventDefault();paint();};b.onpointerenter=e=>{if(e.buttons===1)paint();};b.onclick=paint;$('grid-board').append(b);}}
function renderReferences(){$('references').replaceChildren();for(let [i,ref]of savedImages.entries()){let item=document.createElement('div');item.className='reference';item.title=ref.name+' — reference only, not automatically interpreted';if(ref.objectURL){let img=document.createElement('img');img.src=ref.objectURL;img.alt=ref.name;item.append(img);}else item.textContent=ref.name.slice(0,9);let remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.setAttribute('aria-label','Remove '+ref.name);remove.onclick=()=>{if(ref.objectURL)URL.revokeObjectURL(ref.objectURL);savedImages.splice(i,1);renderReferences();};item.append(remove);$('references').append(item);}}
async function setupAI(){let tier=document.querySelector('[name="ai-tier"]:checked').value;if(tier==='off'){await fetchJSON('/api/ai/clear',{});$('ai-state').textContent='Off';return;}let provider=tier==='local'?'local':$('ai-provider').value;let payload={provider,model:$('ai-model').value.trim(),endpoint:$('ai-endpoint').value.trim(),key:$('ai-key').value,input_price_per_million:$('ai-inprice').value===''?null:Number($('ai-inprice').value),output_price_per_million:$('ai-outprice').value===''?null:Number($('ai-outprice').value)};let result=await fetchJSON('/api/ai/configure',payload);$('ai-key').value='';$('ai-state').textContent=result.provider==='local'?'Local':'Cloud';toast('Session setting stored in memory. Nothing has been sent to the provider yet.',5000);}
async function init(){try{session=await fetchJSON('/api/session');backendBuildId=session.backend_build_id||'missing';initAdvanced();setValues(session.defaults);renderGrid();try{await loadBuild(session.latest||'demo');}catch(e){$('loading').hidden=true;status('No bundled example found. Generate a design to begin.');}window.__ffApp={collect,generate,loadBuild,showTab,get viewer(){return viewer;}};}catch(e){$('loading').hidden=true;toast('Start the included Python server to use the full studio. The offline preview is available separately.\n'+e.message,30000);}}
$('brief-form').onsubmit=e=>{e.preventDefault();generate();};$('understand').onclick=understood;$('confirm-generate').onclick=generate;$('preset').onchange=()=>{currentProject={brief:{...session.defaults,...PRESETS[$('preset').value]}};setValues(currentProject.brief);$('description').value='';$('grid-used').checked=false;savedImages=[];renderReferences();renderSources();status('Example brief selected. Generate to see its actual model.');};$('units').onclick=()=>{let factor=unit==='ft'?304.8/1000:1000/304.8;$('width').value=(Number($('width').value)*factor).toFixed(3);$('depth').value=(Number($('depth').value)*factor).toFixed(3);unit=unit==='ft'?'m':'ft';document.querySelectorAll('.unit').forEach(el=>el.textContent=unit);};
for(let b of document.querySelectorAll('[data-tab]'))b.onclick=()=>showTab(b.dataset.tab);const WALK_HELP='Click the view to look · W A S D move · Shift run · Space jump · C crouch · Stairs change floor · Esc release';
function setModeButtons(mode){document.querySelectorAll('[data-mode]').forEach(q=>q.classList.toggle('active',q.dataset.mode===mode));$('camera-help').textContent=mode==='walk'?WALK_HELP:'Drag to orbit · Scroll to explore · Walk in to explore on foot';}
for(let b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{viewer?.setMode(b.dataset.mode);setModeButtons(b.dataset.mode);if(b.dataset.mode==='walk')$('scene').focus();};for(let b of document.querySelectorAll('[data-view]'))b.onclick=()=>{viewer?.setView(b.dataset.view);document.querySelectorAll('[data-view]').forEach(q=>q.classList.toggle('active',q===b));document.querySelectorAll('[data-mode]').forEach(q=>q.classList.toggle('active',q.dataset.mode==='solid'));$('camera-help').textContent='Drag to orbit · Scroll to explore';};
$('floor').onchange=()=>viewer?.setFloor(Number($('floor').value));$('grade').onchange=()=>viewer?.setGrade($('grade').value);$('quality').onchange=()=>{let q=$('quality').value;if(viewer){viewer.autoQuality=q==='auto';if(q!=='auto')viewer.setQuality(q);}};$('fullscreen').onclick=()=>{let w=document.querySelector('.canvas-wrap');if(document.fullscreenElement)document.exitFullscreen?.();else w.requestFullscreen?.().catch(()=>{});};$('sheet-select').onchange=showSheet;$('reset-camera').onclick=()=>viewer?.reset();$('tour').onclick=()=>{if(!viewer)return;viewer.tour=!viewer.tour;if(viewer.tour)viewer.setMode('tour');$('tour').textContent=viewer.tour?'Ⅱ Pause tour':'▷ Orbit tour';};$('snapshot').onclick=async()=>{if(viewer)download(await viewer.snapshot(),'FloorForge-raster-study.png');};$('export-glb').onclick=async()=>{if(!viewer)return;try{$('export-glb').disabled=true;toast('Preparing the textured scene with its planting for Blender…',8000);download(new Blob([await viewer.exportPresentation()],{type:'model/gltf-binary'}),'FloorForge-presentation.glb');}catch(e){toast(formatError(e));}finally{$('export-glb').disabled=false;}};$('record').onclick=async()=>{if(!viewer)return;try{$('record').disabled=true;toast('Recording a 12-second raster orbit. Keep this tab visible.',12000);download(await viewer.record(),'FloorForge-orbit.webm');}catch(e){toast(e.message);}finally{$('record').disabled=false;}};
 $('clay').onclick=()=>{if(!viewer)return;viewer.setClay(!viewer.clay);$('clay').textContent=viewer.clay?'Clay · planting hidden':'Clay study';};
$('save-project').onclick=()=>download(new Blob([JSON.stringify(collect(),null,2)],{type:'application/json'}),'My-home.floorforge.json');$('open-project').onclick=()=>$('project-file').click();$('project-file').onchange=async e=>{try{let f=e.target.files[0];if(!f)return;if(f.size>2000000)throw Error('Project is larger than 2 MB.');await applyProject(JSON.parse(await f.text()));toast('Project restored. Review and generate to rebuild it.');}catch(e){toast(e.message);}e.target.value='';};$('rename').onclick=()=>{let value=prompt('Project name',$('adv-title').value);if(value?.trim()){$('adv-title').value=value.trim().slice(0,120);$('project-title').textContent=value.trim();}};$('export-top').onclick=()=>{if(!currentScene){toast('Generate a project first.');return;}let a=document.createElement('a');a.href=base+'FloorForge-export.zip';a.download='FloorForge-export.zip';a.click();};
for(let b of document.querySelectorAll('[data-close]'))b.onclick=()=>$(b.dataset.close).close();$('theme-apply').onclick=applyThemeSelection;$('theme-revert').onclick=revertThemeSelection;$('grid-open').onclick=()=>{renderGrid();$('grid-dialog').showModal();};$('grid-clear').onclick=()=>{gridRows=Array.from({length:12},()=>Array(9).fill(''));renderGrid();};$('reference-open').onclick=()=>$('reference-files').click();$('reference-files').onchange=async e=>{for(let f of e.target.files){if(savedImages.length>=12){toast('Twelve references maximum.');break;}if(f.size>10000000||!['image/png','image/jpeg','image/webp'].includes(f.type)){toast('Use JPG, PNG or WebP files up to 10 MB.');continue;}let hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await f.arrayBuffer()))).map(b=>b.toString(16).padStart(2,'0')).join('');savedImages.push({name:f.name,kind:'visual-reference',sha256:hash,note:'Manual reference, not automatically recognised',file:f,objectURL:URL.createObjectURL(f)});}renderReferences();toast('References remain in this browser session. Projects preserve their metadata, not image bytes. Save original images separately. Nothing is sent to AI.',12000);e.target.value='';};
$('ai-open').onclick=()=>$('ai-dialog').showModal();document.querySelectorAll('[name="ai-tier"]').forEach(el=>el.onchange=()=>{let local=el.value==='local';$('ai-config').hidden=el.value==='off';if(local){$('ai-provider').value='local';$('ai-endpoint').value='http://127.0.0.1:8080';$('ai-model').value='Qwen3-8B';}else if(el.value==='cloud'){$('ai-provider').value='anthropic';$('ai-endpoint').value='';$('ai-model').value='claude-sonnet-5';}});$('ai-save').onclick=()=>setupAI().catch(e=>toast(e.message));$('ai-clear').onclick=async()=>{await fetchJSON('/api/ai/clear',{});$('ai-key').value='';$('ai-state').textContent='Off';$('ai-request').hidden=true;toast('Key reference cleared; AI is off. Revoke cloud keys on the provider site too.');};$('ai-estimate').onclick=async()=>{try{let e=await fetchJSON('/api/ai/estimate',{brief:collect().brief,instruction:$('ai-instruction').value}),a=await fetchJSON('/api/ai/status');if(a.provider==='off')throw Error('Configure local or cloud AI first.');$('ai-estimate-result').innerHTML=`<p class="notice">Destination: ${esc(a.endpoint)}<br>Model: ${esc(a.model)}<br>Estimated cost: ${e.estimated_usd===null?'Unknown — verify provider pricing':'$'+e.estimated_usd.toFixed(4)}<br>Only the fused structured brief and this instruction are sent. No reference images, plan files or API keys go to a second provider.</p>`;$('ai-request').hidden=false;}catch(e){toast(e.message);}};$('ai-request').onclick=async()=>{try{$('ai-request').disabled=true;proposed=await fetchJSON('/api/ai/propose',{project:collect(),instruction:$('ai-instruction').value,confirm:true});$('ai-proposal').innerHTML=`<h4 style="margin-top:20px">Validated preliminary proposal</h4><pre>${esc(JSON.stringify(proposed.patch,null,2))}</pre><p>${esc(proposed.rationale)}</p><p>${proposed.critique.map(esc).join('<br>')}</p><p class="micro">Model critique is unverified. Structural and regulatory approval are not implied.</p><button id="apply-proposal" class="secondary wide">Apply to brief, then review</button>`;$('apply-proposal').onclick=async()=>{await applyProject(proposed.candidate_project);$('ai-dialog').close();understood();};}catch(e){toast(e.message);}finally{$('ai-request').disabled=false;}};
init();

// Large view: the 3D canvas takes the whole window (true full screen where the browser allows it, a window-filling
// view everywhere else, including iPhone), carrying the view, mode and lighting controls with it.
const stage=document.querySelector('.canvas-wrap'),stageTools=document.querySelector('#home-panel .canvas-tools'),stageToolsHome=stageTools.parentElement;
function setLargeView(on){if(on===stage.classList.contains('expanded'))return;stage.classList.toggle('expanded',on);document.body.classList.toggle('viewer-expanded',on);if(on){stage.prepend(stageTools);stage.style.setProperty('--tools-h',stageTools.offsetHeight+'px');if(stage.requestFullscreen&&!document.fullscreenElement)stage.requestFullscreen().catch(()=>{});}else{stageToolsHome.insertBefore(stageTools,stage);if(document.fullscreenElement===stage)document.exitFullscreen?.();if(viewer?.focus){viewer.setFocus(false);focusButton(false);}}$('fullscreen').textContent=on?'✕ Exit large view':'⤢ Large view';frameInsets();if(viewer){viewer.resized=true;viewer.dirty=true;}}
// Framing keeps the home clear of the controls laid over the canvas (CSS pixels).
function frameInsets(){if(!viewer)return;const big=stage.classList.contains('expanded'),c=$('scene').getBoundingClientRect();if(big)stage.style.setProperty('--tools-h',stageTools.offsetHeight+'px');let top=big?stageTools.offsetHeight+10:6,bottom=6,right=6;const b=stage.querySelector('.canvas-bottom>div').getBoundingClientRect(),z=stage.querySelector('.zoom-tools').getBoundingClientRect();if(b.height)bottom=Math.max(bottom,c.bottom-b.top+8);if(z.height){const mid=(z.top+z.bottom)/2;if(mid>c.top+c.height*.3&&mid<c.top+c.height*.7)right=c.right-z.left+8;else bottom=Math.max(bottom,c.bottom-z.top+8);}viewer.frameInsets={top,bottom,left:6,right};}
window.addEventListener('resize',frameInsets);
// Focus: the home alone (street and neighbours set aside), filling the whole screen from the current direction.
function focusButton(on){$('focus').textContent=on?'✕ Exit focus':'◎ Focus';$('focus').classList.toggle('active',on);$('focus').setAttribute('aria-pressed',String(on));}
function setFocus(on){if(!viewer)return;if(on){setLargeView(true);frameInsets();viewer.setFocus(true);focusButton(true);}else{viewer.setFocus(false);focusButton(false);setLargeView(false);}}
$('focus').onclick=()=>setFocus(!viewer?.focus);$('zoom-fit').onclick=()=>viewer?.fitHouse({fill:viewer.focus?.94:.86});
// A wider studio: the brief panel folds away (remembered on this device) and the home takes the width.
const workspace=document.querySelector('.workspace');
function setWide(on){workspace.classList.toggle('wide',on);$('brief-toggle').textContent=on?'⇥ Show brief':'⇤ Wider view';$('brief-toggle').setAttribute('aria-pressed',String(on));$('brief-toggle').title=on?'Show the brief panel again':'Hide the brief panel for a wider view of the home';try{localStorage.setItem('ff-wide',on?'1':'0');}catch(e){}if(viewer){viewer.resized=true;viewer.dirty=true;}}
$('brief-toggle').onclick=()=>setWide(!workspace.classList.contains('wide'));try{if(localStorage.getItem('ff-wide')==='1')setWide(true);}catch(e){}
$('fullscreen').onclick=()=>setLargeView(!stage.classList.contains('expanded'));
$('zoom-in').onclick=()=>viewer?.zoom(.7);$('zoom-out').onclick=()=>viewer?.zoom(1/.7);
// Capture renders a large still (3840 px wide) of exactly the current view.
$('snapshot').onclick=async()=>{if(!viewer)return;$('snapshot').disabled=true;toast('Rendering a large 3840-pixel still of this view…',6000);try{await new Promise(r=>setTimeout(r,60));download(await viewer.snapshot({width:3840}),'FloorForge-view-large.png');}catch(e){toast(e.message);}finally{$('snapshot').disabled=false;}};

// Drawing sheets: zoom (buttons, Ctrl/⌘ + scroll, double-click), drag to pan, and a large view.
const sheetHolder=document.querySelector('.drawing-holder'),sheetImage=$('drawing-image');let sheetZoom=1,sheetDrag=null;
function zoomSheet(level,cx,cy){const r=sheetHolder.getBoundingClientRect();cx=cx??r.left+r.width/2;cy=cy??r.top+r.height/2;const fx=(sheetHolder.scrollLeft+cx-r.left)/Math.max(1,sheetHolder.scrollWidth),fy=(sheetHolder.scrollTop+cy-r.top)/Math.max(1,sheetHolder.scrollHeight);sheetZoom=Math.min(8,Math.max(1,level));if(sheetZoom<1.05)sheetZoom=1;sheetHolder.classList.toggle('zoomed',sheetZoom>1);sheetImage.style.width=sheetZoom>1?sheetZoom*100+'%':'';$('sheet-fit').textContent=sheetZoom>1?Math.round(sheetZoom*100)+'%':'Fit';sheetHolder.scrollLeft=fx*sheetHolder.scrollWidth-(cx-r.left);sheetHolder.scrollTop=fy*sheetHolder.scrollHeight-(cy-r.top);}
$('sheet-zoom-in').onclick=()=>zoomSheet(sheetZoom*1.5);$('sheet-zoom-out').onclick=()=>zoomSheet(sheetZoom/1.5);$('sheet-fit').onclick=()=>zoomSheet(1);
sheetHolder.addEventListener('wheel',e=>{if(!(e.ctrlKey||e.metaKey))return;e.preventDefault();zoomSheet(sheetZoom*(e.deltaY<0?1.2:1/1.2),e.clientX,e.clientY);},{passive:false});
sheetImage.addEventListener('dblclick',e=>zoomSheet(sheetZoom>1?1:2.5,e.clientX,e.clientY));
sheetHolder.addEventListener('pointerdown',e=>{if(sheetZoom<=1||e.button!==0||e.target.closest('button'))return;sheetDrag={x:e.clientX,y:e.clientY,l:sheetHolder.scrollLeft,t:sheetHolder.scrollTop,id:e.pointerId};sheetHolder.setPointerCapture(e.pointerId);sheetHolder.classList.add('panning');});
sheetHolder.addEventListener('pointermove',e=>{if(!sheetDrag||e.pointerId!==sheetDrag.id)return;sheetHolder.scrollLeft=sheetDrag.l-(e.clientX-sheetDrag.x);sheetHolder.scrollTop=sheetDrag.t-(e.clientY-sheetDrag.y);});
const endSheetDrag=()=>{sheetDrag=null;sheetHolder.classList.remove('panning');};sheetHolder.addEventListener('pointerup',endSheetDrag);sheetHolder.addEventListener('pointercancel',endSheetDrag);
function setSheetLarge(on){sheetHolder.classList.toggle('expanded',on);document.body.classList.toggle('viewer-expanded',on||stage.classList.contains('expanded'));$('sheet-close').hidden=!on;$('sheet-large').textContent=on?'✕ Exit large view':'⤢ Large view';if(on&&sheetHolder.requestFullscreen&&!document.fullscreenElement)sheetHolder.requestFullscreen().catch(()=>{});if(!on&&document.fullscreenElement===sheetHolder)document.exitFullscreen?.();}
$('sheet-large').onclick=()=>setSheetLarge(!sheetHolder.classList.contains('expanded'));$('sheet-close').onclick=()=>setSheetLarge(false);
$('sheet-select').addEventListener('change',()=>zoomSheet(1));

document.addEventListener('fullscreenchange',()=>{if(document.fullscreenElement)return;if(stage.classList.contains('expanded'))setLargeView(false);if(sheetHolder.classList.contains('expanded'))setSheetLarge(false);});
document.addEventListener('keydown',e=>{if(e.key!=='Escape'||document.pointerLockElement)return;if(sheetHolder.classList.contains('expanded'))setSheetLarge(false);else if(stage.classList.contains('expanded')&&viewer?.mode!=='walk')setLargeView(false);});
