/* FloorForge authored WebGL2 inspection renderer. No third-party network requests.
   Raster study renderer, not a photoreal/path-tracing engine. Z-up, metres. */
(() => {'use strict';
const sub=(a,b)=>a.map((x,i)=>x-b[i]),add=(a,b)=>a.map((x,i)=>x+b[i]),mul=(a,s)=>a.map(x=>x*s),dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm=a=>mul(a,1/(Math.hypot(...a)||1));
function mm(a,b){let o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o;}
function view(eye,target){let z=norm(sub(eye,target)),x=norm(cross([0,0,1],z));if(Math.hypot(...x)<.01)x=[1,0,0];let y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]);}
function perspective(fov,aspect,n=.05,f=400){let s=1/Math.tan(fov*Math.PI/360);return new Float32Array([s/aspect,0,0,0,0,s,0,0,0,0,(f+n)/(n-f),-1,0,0,2*f*n/(n-f),0]);}
function ortho(l,r,b,t,n,f){return new Float32Array([2/(r-l),0,0,0,0,2/(t-b),0,0,0,0,-2/(f-n),0,-(r+l)/(r-l),-(t+b)/(t-b),-(f+n)/(f-n),1]);}
function rotation(v,r){let [x,y,z]=v,[a,b,c]=r;let yy=y*Math.cos(a)-z*Math.sin(a);z=y*Math.sin(a)+z*Math.cos(a);y=yy;let xx=x*Math.cos(b)+z*Math.sin(b);z=-x*Math.sin(b)+z*Math.cos(b);x=xx;return [x*Math.cos(c)-y*Math.sin(c),x*Math.sin(c)+y*Math.cos(c),z];}
const vert=`#version 300 es
precision highp float;layout(location=0)in vec3 p;layout(location=1)in vec3 normal;uniform mat4 vp;uniform mat4 lightVP;out vec3 W;out vec3 N;out vec4 LP;void main(){W=p;N=normal;LP=lightVP*vec4(p,1.);gl_Position=vp*vec4(p,1.);}`;
const frag=`#version 300 es
precision highp float;in vec3 W;in vec3 N;in vec4 LP;out vec4 outColor;uniform vec3 color;uniform vec3 eye;uniform vec3 sun;uniform vec3 background;uniform float roughness;uniform float metallic;uniform float opacity;uniform float emission;uniform float clipZ;uniform int clipWall;uniform int textureKind;uniform int grade;uniform sampler2D shadowMap;uniform vec3 lightPos[16];uniform int lightCount;
float hash(vec3 p){return fract(sin(dot(p,vec3(127.1,311.7,74.7)))*43758.5453);}
float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);float a=mix(hash(i),hash(i+vec3(1,0,0)),f.x),b=mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),c=mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),d=mix(hash(i+vec3(0,1,1)),hash(i+vec3(1,1,1)),f.x);return mix(mix(a,b,f.y),mix(c,d,f.y),f.z);}
vec3 aces(vec3 x){return clamp((x*(2.51*x+.03))/(x*(2.43*x+.59)+.14),0.,1.);}
float visibility(){vec3 q=LP.xyz/LP.w*.5+.5;if(q.z>1.||q.z<0.||q.x<0.||q.x>1.||q.y<0.||q.y>1.)return 1.;float bias=max(.0010*(1.-dot(normalize(N),sun)),.0005),v=0.;for(int x=-1;x<=1;x++)for(int y=-1;y<=1;y++){float d=texture(shadowMap,q.xy+vec2(x,y)/2048.).r;v+=q.z-bias<d?1.:.12;}return v/9.;}
void main(){if(clipWall==1&&W.z>clipZ)discard;vec3 n=normalize(N);if(!gl_FrontFacing)n=-n;vec3 c=pow(color,vec3(2.2));float grain=noise(W*9.);
if(textureKind==1)c*=.94+.12*grain;
if(textureKind==2){float g=sin(W.x*42.+sin(W.y*3.)*2.+sin(W.x*4.)*.7);c*=.89+.13*g+.035*grain;}
if(textureKind==3){vec2 uv=abs(n.z)>.7?W.xy:abs(n.x)>.7?W.yz:W.xz;vec2 q=fract(uv/.65);float grout=step(q.x,.004)+step(q.y,.004);c*=mix(1.,.77,clamp(grout,0.,1.));c*=.96+.08*hash(floor(vec3(uv/.65,0.)));}
if(textureKind==4)c*=.91+.13*noise(W*3.5);
if(textureKind==5){float a=sin(W.x*50.)*sin(W.y*52.)*sin(W.z*51.);c*=.94+.045*a;}
float nl=max(dot(n,sun),0.),sv=visibility(),night=grade==2?1.:0.;vec3 sky=mix(vec3(.50,.58,.66),vec3(.16,.24,.40),night);float hemi=.35+.65*(n.z*.5+.5);vec3 illumination=sky*(.27+.34*hemi);vec3 sunColor=grade==1?vec3(1.,.80,.56):grade==2?vec3(.24,.30,.44):vec3(1.,.95,.83);illumination+=sunColor*nl*sv*(grade==2?.28:2.6);
for(int i=0;i<16;i++){if(i>=lightCount)break;vec3 l=lightPos[i]-W;float d=length(l);illumination+=vec3(1.,.63,.29)*max(dot(n,normalize(l)),0.)/(1.+d*d)*(grade==2?2.7:.4);}
vec3 v=normalize(eye-W),h=normalize(v+sun);float spec=pow(max(dot(n,h),0.),mix(120.,8.,roughness))*nl*sv*(1.-roughness)*.42;vec3 lit=c*illumination+mix(vec3(spec),c*spec,metallic)+c*emission*(grade==2?1.3:.65);float fog=1.-exp(-max(length(eye-W)-65.,0.)*.002);vec3 rgb=pow(aces(lit),vec3(1./2.2));rgb=mix(rgb,background,fog);outColor=vec4(rgb,opacity);}`;
const depthFrag=`#version 300 es
precision highp float;in vec3 W;uniform float clipZ;uniform int clipWall;void main(){if(clipWall==1&&W.z>clipZ)discard;}`;
function program(gl,vs,fs){let p=gl.createProgram();for(let [type,src]of [[gl.VERTEX_SHADER,vs],[gl.FRAGMENT_SHADER,fs]]){let sh=gl.createShader(type);gl.shaderSource(sh,src);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(sh));gl.attachShader(p,sh);gl.deleteShader(sh);}gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p;}
function pointIn(p,poly){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){let a=poly[i],b=poly[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside;}
function segmentDistance(p,a,b){let d=sub(b,a),t=Math.max(0,Math.min(1,dot(sub(p,a),d)/(dot(d,d)||1)));return Math.hypot(...sub(p,add(a,mul(d,t))));}
class FloorForgeViewer{
constructor(canvas,{onStatus=()=>{}}={}){this.canvas=canvas;this.onStatus=onStatus;this.gl=canvas.getContext('webgl2',{antialias:true,alpha:false,preserveDrawingBuffer:true});if(!this.gl)throw Error('WebGL2 is unavailable. The drawing and project exports still work.');let g=this.gl;this.main=program(g,vert,frag);this.depth=program(g,vert,depthFrag);this.locations=new Map();this.groups=[];this.mode='solid';this.floor=0;this.grade=0;this.clay=false;this.keys=new Set();this.radius=.22;this.yaw=Math.PI/2;this.pitch=0;this.orbitTheta=-.90;this.orbitPhi=.63;this.distance=26;this.target=[5,6,2];this.dirty=true;this.frames=0;this.last=performance.now();this.disposed=false;this.listeners=[];
this.shadow=g.createTexture();g.bindTexture(g.TEXTURE_2D,this.shadow);g.texImage2D(g.TEXTURE_2D,0,g.DEPTH_COMPONENT24,2048,2048,0,g.DEPTH_COMPONENT,g.UNSIGNED_INT,null);for(let x of [g.TEXTURE_MIN_FILTER,g.TEXTURE_MAG_FILTER])g.texParameteri(g.TEXTURE_2D,x,g.NEAREST);for(let x of [g.TEXTURE_WRAP_S,g.TEXTURE_WRAP_T])g.texParameteri(g.TEXTURE_2D,x,g.CLAMP_TO_EDGE);this.fbo=g.createFramebuffer();g.bindFramebuffer(g.FRAMEBUFFER,this.fbo);g.framebufferTexture2D(g.FRAMEBUFFER,g.DEPTH_ATTACHMENT,g.TEXTURE_2D,this.shadow,0);g.drawBuffers([g.NONE]);g.readBuffer(g.NONE);if(g.checkFramebufferStatus(g.FRAMEBUFFER)!==g.FRAMEBUFFER_COMPLETE)throw Error('Shadow framebuffer unavailable');g.bindFramebuffer(g.FRAMEBUFFER,null);
const listen=(target,name,fn,opt)=>{target.addEventListener(name,fn,opt);this.listeners.push(()=>target.removeEventListener(name,fn,opt));};let drag=null;
listen(canvas,'pointerdown',e=>{canvas.focus();drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);});listen(canvas,'pointerup',()=>drag=null);listen(canvas,'pointercancel',()=>drag=null);
listen(canvas,'pointermove',e=>{if(!drag)return;let dx=e.clientX-drag[0],dy=e.clientY-drag[1];drag=[e.clientX,e.clientY];this.tour=false;if(this.mode==='walk'){this.yaw-=dx*.006;this.pitch=Math.max(-1.2,Math.min(1.2,this.pitch-dy*.004));}else{this.orbitTheta-=dx*.007;this.orbitPhi=Math.max(.08,Math.min(1.55,this.orbitPhi+dy*.006));}this.dirty=true;});
listen(canvas,'wheel',e=>{e.preventDefault();this.distance=Math.max(3,Math.min(110,this.distance*Math.exp(e.deltaY*.001)));this.dirty=true;},{passive:false});
listen(canvas,'keydown',e=>{if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Escape'].includes(e.code)){e.preventDefault();this.keys.add(e.code);}if(e.code==='Escape')this.setMode('solid');});listen(canvas,'keyup',e=>this.keys.delete(e.code));listen(canvas,'blur',()=>this.keys.clear());
this.resize=new ResizeObserver(()=>this.dirty=true);this.resize.observe(canvas);this.tick=t=>{if(this.disposed)return;let dt=Math.min(.04,(t-this.last)/1000);this.last=t;if(this.mode==='walk'&&this.keys.size){this.move(dt);this.dirty=true;}if(this.tour){this.orbitTheta+=dt*.09;this.dirty=true;}if(this.dirty&&this.scene){this.draw();this.frames++;this.dirty=false;}this.raf=requestAnimationFrame(this.tick);};this.raf=requestAnimationFrame(this.tick);
}
loc(p,name){let key=(p===this.main?'m':'d')+name;if(!this.locations.has(key))this.locations.set(key,this.gl.getUniformLocation(p,name));return this.locations.get(key);}
setScene(data){if(data.up!=='Z'||data.units!=='m')throw Error('Scene must use Z-up metres.');this.scene=data;this.clay=false;this.viewName='hero';let gl=this.gl;for(let q of this.groups){gl.deleteBuffer(q.vbo);gl.deleteVertexArray(q.vao);}this.groups=[];const buckets=new Map();
for(let node of data.nodes){let asset=data.assets[node.asset];if(!asset)throw Error('Missing geometry asset');let key=[node.material,node.floor,node.role].join('|');if(!buckets.has(key))buckets.set(key,{data:[],material:node.material,floor:node.floor,role:node.role});let out=buckets.get(key).data;
const ps=asset.vertices.map(v=>add(rotation(v.map((x,i)=>x*node.scale[i]),node.rotation),node.position));let ns=asset.normals?.map(n=>norm(rotation(n.map((x,i)=>x/node.scale[i]),node.rotation)));
for(let f of asset.faces){let flat=norm(cross(sub(ps[f[1]],ps[f[0]]),sub(ps[f[2]],ps[f[0]])));for(let i of f){out.push(...ps[i],...(ns?ns[i]:flat));}}
}
for(let q of buckets.values()){let arr=new Float32Array(q.data),vao=gl.createVertexArray(),vbo=gl.createBuffer();gl.bindVertexArray(vao);gl.bindBuffer(gl.ARRAY_BUFFER,vbo);gl.bufferData(gl.ARRAY_BUFFER,arr,gl.STATIC_DRAW);for(let i=0;i<2;i++){gl.enableVertexAttribArray(i);gl.vertexAttribPointer(i,3,gl.FLOAT,false,24,i*12);}this.groups.push({...q,data:null,vao,vbo,count:arr.length/6});}gl.bindVertexArray(null);this.floor=0;this.reset();this.dirty=true;this.onStatus(`${data.nodes.length.toLocaleString()} objects · ${data.assets?Object.keys(data.assets).length:0} shared meshes · local raster study`);}
reset(){if(!this.scene)return;const c=this.scene.cameras[this.mode==='dollhouse'||this.mode==='plan'?'dollhouse':this.mode==='walk'?'interior':'hero'];this.target=[...c.target];let delta=sub(c.position,c.target);this.distance=Math.hypot(...delta);this.orbitTheta=Math.atan2(delta[1],delta[0]);this.orbitPhi=Math.asin(delta[2]/this.distance);if(this.mode==='plan')this.orbitPhi=1.55;if(this.mode==='walk'){this.walk=[...c.position];this.walk[2]=this.floor*this.scene.floor_height+1.6;this.yaw=Math.atan2(c.target[1]-c.position[1],c.target[0]-c.position[0]);this.pitch=0;}this.dirty=true;}
setMode(mode){if(!['solid','dollhouse','plan','walk','tour'].includes(mode))return;this.tour=mode==='tour';this.mode=this.tour?'solid':mode;this.reset();}
setFloor(f){this.floor=Math.max(0,Math.min(this.scene.storeys-1,Number(f)));if(this.mode==='walk'){this.reset();this.walk[2]=this.floor*this.scene.floor_height+1.6;}this.dirty=true;}
setGrade(grade){this.grade={day:0,golden:1,dusk:2}[grade]??0;this.dirty=true;}
setClay(on=true){this.clay=Boolean(on);this.dirty=true;this.onStatus(this.clay?'Neutral clay · decorative planting hidden':'Geometry screened · regulatory and structural approval remain open.');}
setView(name='hero'){if(!this.scene)return;if(name==='hero'){this.viewName='hero';this.tour=false;this.mode='solid';this.reset();this.onStatus('Hero inspection · same day lighting and 43° field of view');return;}let fp=this.scene.footprint,xs=fp.map(p=>p[0]),ys=fp.map(p=>p[1]),W=Math.max(...xs)-Math.min(...xs),D=Math.max(...ys)-Math.min(...ys),H=this.scene.floor_height,mid=[(Math.min(...xs)+Math.max(...xs))/2,(Math.min(...ys)+Math.max(...ys))/2,Math.min(H*1.15+0.2,4.2)];let views={front:{target:[mid[0],-.2,mid[2]],theta:-Math.PI/2,phi:.32,distance:Math.max(W,D)*1.05},left:{target:[mid[0],D*.24,mid[2]],theta:Math.PI,phi:.30,distance:Math.max(W,D)*1.12},right:{target:[mid[0],D*.24,mid[2]],theta:0,phi:.30,distance:Math.max(W,D)*1.12},entrance:{target:[this.scene.entry[0],-.65,1.65],theta:-Math.PI/2,phi:.20,distance:7.2},balcony:{target:[W*.61,-1.05,H*1.78],theta:-Math.PI/2,phi:.38,distance:6.8}};let v=views[name]||views.front;this.tour=false;this.mode='solid';this.viewName=name;this.target=[...v.target];this.orbitTheta=v.theta;this.orbitPhi=v.phi;this.distance=v.distance;this.dirty=true;this.onStatus(`${name[0].toUpperCase()+name.slice(1)} inspection · same day lighting and 43° field of view`);}
blocked(x,y){if(!this.scene)return true;let b=this.scene.bounds;if(x<b[0]||x>b[3]||y<b[1]||y>b[4])return true;for(let c of this.scene.colliders){if(c.floor!==this.floor)continue;let p=c.polygon;if(pointIn([x,y],p))return true;for(let i=0;i<p.length;i++)if(segmentDistance([x,y],p[i],p[(i+1)%p.length])<this.radius)return true;}return false;}
move(dt){let k=this.keys,forward=(k.has('KeyW')||k.has('ArrowUp')?1:0)-(k.has('KeyS')||k.has('ArrowDown')?1:0),side=(k.has('KeyD')||k.has('ArrowRight')?1:0)-(k.has('KeyA')||k.has('ArrowLeft')?1:0);let speed=1.35*dt/(Math.hypot(forward,side)||1),dx=(Math.cos(this.yaw)*forward+Math.sin(this.yaw)*side)*speed,dy=(Math.sin(this.yaw)*forward-Math.cos(this.yaw)*side)*speed;let steps=Math.max(1,Math.ceil(Math.hypot(dx,dy)/.06));for(let i=0;i<steps;i++){let x=this.walk[0]+dx/steps,y=this.walk[1]+dy/steps;if(!this.blocked(x,this.walk[1]))this.walk[0]=x;if(!this.blocked(this.walk[0],y))this.walk[1]=y;} }
visible(q){if(this.clay&&['landscape','planter'].includes(q.role))return false;if(['dollhouse','plan'].includes(this.mode)){if(q.floor>this.floor)return false;if(['roof','ceiling','railing','canopy','pipe','accent','fin','screen','band','pergola'].includes(q.role))return false;if(q.floor>=0&&q.floor<this.floor&&q.role!=='wall'&&q.role!=='floor')return false;if(['window','glazing','curtain','door'].includes(q.role))return false;}return true;}
camera(){if(this.mode==='walk'){let target=add(this.walk,[Math.cos(this.yaw)*Math.cos(this.pitch),Math.sin(this.yaw)*Math.cos(this.pitch),Math.sin(this.pitch)]);return {eye:this.walk,target,fov:66};}let d=this.distance,p=this.orbitPhi,t=this.orbitTheta;return{eye:add(this.target,[d*Math.cos(p)*Math.cos(t),d*Math.cos(p)*Math.sin(t),d*Math.sin(p)]),target:this.target,fov:43};}
draw(){let g=this.gl,c=this.canvas,ratio=Math.min(devicePixelRatio||1,1.6),w=Math.round(c.clientWidth*ratio),h=Math.round(c.clientHeight*ratio);if(!w||!h)return;if(c.width!==w||c.height!==h){c.width=w;c.height=h;}let camera=this.camera(),vp=mm(perspective(camera.fov,w/h),view(camera.eye,camera.target)),b=this.scene.bounds,center=[(b[0]+b[3])/2,(b[1]+b[4])/2,1.5],radius=Math.max(b[3]-b[0],b[4]-b[1])*1.05,sun=norm(this.scene.solar.vector_local);if(sun[2]<.12)sun=norm([sun[0],sun[1],.18]);let lightVP=mm(ortho(-radius,radius,-radius,radius,1,160),view(add(center,mul(sun,65)),center));let clip=(['dollhouse','plan'].includes(this.mode)?this.floor*this.scene.floor_height+1.18:1e5);
g.enable(g.DEPTH_TEST);g.disable(g.CULL_FACE);g.disable(g.BLEND);g.bindFramebuffer(g.FRAMEBUFFER,this.fbo);g.viewport(0,0,2048,2048);g.clear(g.DEPTH_BUFFER_BIT);g.useProgram(this.depth);g.uniformMatrix4fv(this.loc(this.depth,'vp'),false,lightVP);g.uniform1f(this.loc(this.depth,'clipZ'),clip);
for(let q of this.groups){if(!this.visible(q)||this.scene.materials[q.material].alpha<1)continue;g.uniform1i(this.loc(this.depth,'clipWall'),['wall','joinery','accent','fin','screen','pipe'].includes(q.role)?1:0);g.bindVertexArray(q.vao);g.drawArrays(g.TRIANGLES,0,q.count);}g.bindFramebuffer(g.FRAMEBUFFER,null);g.viewport(0,0,w,h);let bg=this.grade===2?[.19,.25,.32]:[.89,.90,.86];g.clearColor(...bg,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);g.useProgram(this.main);let U=(name,fn,...args)=>g[fn](this.loc(this.main,name),...args);U('vp','uniformMatrix4fv',false,vp);U('lightVP','uniformMatrix4fv',false,lightVP);U('eye','uniform3fv',camera.eye);U('sun','uniform3fv',sun);U('background','uniform3fv',bg);U('grade','uniform1i',this.grade);U('clipZ','uniform1f',clip);g.activeTexture(g.TEXTURE0);g.bindTexture(g.TEXTURE_2D,this.shadow);U('shadowMap','uniform1i',0);let lights=this.scene.lights.slice(0,16);U('lightCount','uniform1i',lights.length);let lp=new Float32Array(48);lights.forEach((l,i)=>lp.set(l.position,i*3));U('lightPos[0]','uniform3fv',lp);
let transparent=[];let render=q=>{let m=this.scene.materials[q.material],rgb=[1,3,5].map(i=>parseInt(m.color.slice(i,i+2),16)/255);if(this.clay){rgb=[.62,.61,.56];}U('color','uniform3fv',rgb);U('roughness','uniform1f',this.clay?.92:m.roughness??.8);U('metallic','uniform1f',this.clay?0:m.metallic??0);U('opacity','uniform1f',this.clay?1:m.alpha??1);U('emission','uniform1f',this.clay?0:m.emission??0);U('clipWall','uniform1i',['wall','joinery','accent','fin','screen','pipe'].includes(q.role)?1:0);U('textureKind','uniform1i',this.clay?0:({plaster:1,stone:1,concrete:1,wood:2,tile:3,paver:3,grass:4,asphalt:4,fabric:5})[m.texture]??0);g.bindVertexArray(q.vao);g.drawArrays(g.TRIANGLES,0,q.count);};
for(let q of this.groups){if(!this.visible(q))continue;if((this.scene.materials[q.material].alpha??1)<1)transparent.push(q);else render(q);}g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE_MINUS_SRC_ALPHA);g.depthMask(false);for(let q of transparent)render(q);g.depthMask(true);g.disable(g.BLEND);g.bindVertexArray(null);this.lastCamera=camera;}
async snapshot(){this.draw();return new Promise(resolve=>this.canvas.toBlob(resolve,'image/png'));}
async record(seconds=12){if(!this.canvas.captureStream||!window.MediaRecorder)throw Error('Video recording is unavailable in this browser.');let stream=this.canvas.captureStream(24),type=MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm',rec=new MediaRecorder(stream,{mimeType:type,videoBitsPerSecond:6000000}),chunks=[];let old=this.tour;this.setMode('tour');return new Promise((resolve,reject)=>{rec.ondataavailable=e=>chunks.push(e.data);rec.onerror=reject;rec.onstop=()=>{this.tour=old;stream.getTracks().forEach(t=>t.stop());resolve(new Blob(chunks,{type:'video/webm'}));};rec.start();setTimeout(()=>rec.stop(),seconds*1000);});}
destroy(){this.disposed=true;cancelAnimationFrame(this.raf);this.resize.disconnect();this.listeners.forEach(fn=>fn());let g=this.gl;for(let q of this.groups){g.deleteBuffer(q.vbo);g.deleteVertexArray(q.vao);}g.deleteTexture(this.shadow);g.deleteFramebuffer(this.fbo);g.deleteProgram(this.main);g.deleteProgram(this.depth);}
}
window.FloorForgeViewer=FloorForgeViewer;window.FloorForgeMath={pointIn,segmentDistance,rotation};
})();
